In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.DataFrame({'text':['people watch campusx' , 'campusx watch people' , 'people write comment' , 'campusx write comment'],'output':[1,1,0,0]})

In [4]:
df

text  output
0   people watch campusx       1
1   campusx watch people       1
2   people write comment       0
3  campusx write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df['text'])

In [7]:
## vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [8]:
print(bow[0].toarray())
print(bow[1].toarray())


[[1 0 1 1 0]]
[[1 0 1 1 0]]


In [9]:
 ## forany traing data and handle oov problem
cv.transform(["campusx with and write comment of campusx"]).toarray()

array([[2, 1, 0, 0, 1]])

**handle out of vocabulary problem **

**N_GRAMS TECHNIQUE OF FEATURE EXTRACTION**

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

## (2,2) represent the bigram, so we can extend this like


In [11]:
bow = cv.fit_transform(df['text'])

In [12]:
## vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'watch people': 5, 'people write': 3, 'write comment': 6, 'campusx write': 1}


In [13]:
print(bow[0].toarray())
print(bow[0].toarray())

[[0 0 1 0 1 0 0]]
[[0 0 1 0 1 0 0]]


In [14]:
 ## for (1,2) gram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,2))


In [15]:
bow = cv.fit_transform(df['text'])

In [16]:
## vocab
print(cv.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'watch people': 9, 'write': 10, 'comment': 3, 'people write': 6, 'write comment': 11, 'campusx write': 2}


In [17]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 1 1 0 1 1 0 0 0]]
[[1 1 0 0 1 0 0 1 0 1 0 0]]


**TF AND IDF FEATURE EXTRACTION TECHNIQUE**

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.53256952, 0.        , 0.53256952, 0.65782931, 0.        ],
       [0.53256952, 0.        , 0.53256952, 0.65782931, 0.        ],
       [0.        , 0.61366674, 0.49681612, 0.        , 0.61366674],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [19]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.22314355 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
